# Generated by Django 6.0.4 on 2026-05-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_content_message_body_message_sender_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['seq', 'timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
